version: '2'

services:
        elasticsearch:
                # image: dev/my-elasticsearch-v1
                image: elastest/eim-elasticsearch:0.1
                ports:
                        - "9200:9200"
                        - "9300:9300"
                hostname: elasticsearch
                networks:
                        - elastest
        logstash:
                # image: dev/my-logstash-v1
                image: elastest/eim-logstash:0.1
                #volumes:
                #        - ./logstash-docker/logstash.conf:/logstash/logstash.conf
                ports:
                        - "5044:5044"
                depends_on: 
                        - elasticsearch
                links:
                        - elasticsearch
                hostname: logstash
                networks:
                        - elastest

        kibana:
                # image: dev/my-kibana-v1
                image: elastest/eim-kibana:0.1
                ports: 
                        - "5601:5601"
                depends_on:
                        - logstash
                links:
                        - elasticsearch
                hostname: kibana
                networks:
                        - elastest

        sut:
                # image: dev/my-sut-v1_1
                image: elastest/eim-sut:0.1
                volumes:
                        - static-content:/tmp/ssh
                depends_on:
                        - kibana
                stdin_open: true
                tty: true
                #hostname: sut
                networks:
                        - elastest

        eim:
                # image: dev/my-eim-v1_1
                image: elastest/eim:0.1
                volumes:
                        - static-content:/tmp/ssh 
                depends_on:
                        - sut
                stdin_open: true
                tty: true
                expose:
                        - 8080
                ports:
                        - "8080:8080" 
                #hostname: eim
                networks:
                        - elastest

volumes:
        static-content:

networks:
        elastest:
                # external: true
                driver: bridge
