version: '2.1'

services:
        eim-mongo:
                image: mvertes/alpine-mongo
                expose: 
                        - 27017
                ports: 
                        - "27017:27017"
                hostname: eim-mongo 
                stdin_open: true
                tty: true
                networks:
                        - elastest
        eim:
                image: elastest/eim:0.1
                depends_on:
                        - eim-mongo
                links:
                        - eim-mongo
                stdin_open: true
                tty: true
                environment:
                        - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
                        - ET_EDM_MYSQL_HOST=edm-mysql
                        - ET_EDM_MYSQL_PORT=3306
                        - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
                        - ET_EDM_API=http://edm:37003/
                        - ET_EPM_API=http://epm:37002/
                        - ET_ETM_API=http://etm:37006/
                        - ET_ESM_API=http://esm:37005/
                expose:
                        - 8080
                ports:
                        - "37004:8080" 
                networks:
                        - elastest

networks:
        elastest:
                driver: bridge
